# 🧑‍💻 NumPy Complete Guided Project
**Instructor / Student Colab Notebook** – covers *all* key concepts from `Numpy‑1` to `Numpy‑5`.

*Generated: 08 Aug 2025*


**Table of Contents**

1. [Setup](#setup)  
2. [Array Creation & Dtypes](#creation)  
3. [Array Attributes & Inspection](#attributes)  
4. [Indexing, Slicing, Fancy Indexing](#indexing)  
5. [Reshaping, Transpose & Copies vs Views](#reshape)  
6. [Joining, Splitting, Set & Sorting Ops](#join)  
7. [Arithmetic Ops, Universal Functions](#arithmetic)  
8. [Broadcasting (Rules + Examples)](#broadcast)  
9. [Statistics & Aggregations](#stats)  
10. [Random Numbers & Reproducibility](#random)  
11. [Structured / Recarrays](#structured)  
12. [Linear Algebra Essentials](#linalg)  
13. [File I/O (`npy`, `npz`, `txt`)](#io)  
14. [Datetime64 & Timedelta64](#datetime)  
15. [Masked Arrays & NaNs](#mask)  
16. [Mini‑Project — Fitness Data Analysis](#project)  
17. [Conclusion & Next Steps](#conclusion)  


## <a name='setup'></a>1️⃣ Setup

In [ ]:
import numpy as np, math, os, pathlib, types, textwrap, random
print('NumPy version:', np.__version__)

## <a name='creation'></a>2️⃣ Array Creation & Dtypes

Key functions: `np.array`, `np.arange`, `np.linspace`, `zeros`, `ones`, `full`, `eye`, `identity`, `diag`, `empty`

In [ ]:
# EXAMPLE
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.linspace(0, 1, 6)
arr3 = np.full((2,3), 7.5)
print(arr1, arr2, arr3, sep="\n")
print("dtypes:", arr1.dtype, arr2.dtype)


In [1]:
# 🖊️ TODO: create a 10×10 chessboard pattern using zeros & ones

import numpy as np


chessboard = np.zeros((10, 10), dtype=int)
chessboard[1::2, 0::2] = 1
chessboard[0::2, 1::2] = 1
print(chessboard)




[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


## <a name='attributes'></a>3️⃣ Array Attributes & Inspection

`shape`, `ndim`, `size`, `dtype`, `itemsize`, `nbytes`

In [ ]:
M = np.arange(12).reshape(3,4)
print('shape', M.shape, 'ndim', M.ndim, 'size', M.size, 'itemsize', M.itemsize, 'total bytes', M.nbytes)


In [ ]:
# 🖊️ TODO: check memory footprint of a 1000×1000 float64 array


## <a name='indexing'></a>4️⃣ Indexing, Slicing & Fancy Indexing

In [ ]:
a = np.arange(1,26).reshape(5,5)
print(a[:, 0])     # first column
print(a[::2, ::2]) # every 2nd row/col
mask = (a % 3 == 0)
print('multiples of 3:', a[mask])


In [2]:
# 🖊️ TODO: use fancy indexing to swap first and last rows of `a`
import numpy as np

a = np.arange(1, 26).reshape(5, 5)

# Use fancy indexing to swap first and last rows
rows = [4, 1, 2, 3, 0]  # Swap the first row (index 0) with the last row (index 4)
swapped_a = a[rows, :]

print(swapped_a)



[[21 22 23 24 25]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 1  2  3  4  5]]


## <a name='reshape'></a>5️⃣ Reshaping, Transpose & Copies vs Views

In [ ]:
b = np.arange(8)
B = b.reshape(2,4)
B[0,0] = 99
print('b is modified:', b)
C = b.reshape(2,4).copy()
C[0,0] = -1
print('b unchanged with copy:', b)


In [3]:
# 🖊️ TODO: Flatten a 3‑D array into 1‑D using both `ravel` and `flatten`; observe copy vs view.
import numpy as np

# Create a 3-D array
x = np.arange(2*3*4).reshape(2, 3, 4)
print("Original x:\n", x)

# 1) ravel: returns a view when possible (no copy)
x_ravel = x.ravel()
print("\nravel output (before modifying x):\n", x_ravel)

# Modify the original array
x[0, 0, 0] = 999
print("\nAfter modifying x[0,0,0] = 999")
print("x_ravel reflects change (view when possible):\n", x_ravel)

# 2) flatten: always returns a copy
x_flatten = x.flatten()
print("\nflatten output (before modifying x again):\n", x_flatten)

# Modify the original array again
x[0, 0, 1] = 888
print("\nAfter modifying x[0,0,1] = 888")
print("x_flatten does NOT change (it's a copy):\n", x_flatten)

# For clarity, show current x
print("\nCurrent x:\n", x)



Original x:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

ravel output (before modifying x):
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

After modifying x[0,0,0] = 999
x_ravel reflects change (view when possible):
 [999   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]

flatten output (before modifying x again):
 [999   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]

After modifying x[0,0,1] = 888
x_flatten does NOT change (it's a copy):
 [999   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]

Current x:
 [[[999 888   2   3]
  [  4   5   6   7]
  [  8   9  10  11]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]]]


## <a name='join'></a>6️⃣ Joining, Splitting, Set & Sorting Ops

In [ ]:
x = np.array([1,3,5]); y = np.array([2,4,6])
xy = np.concatenate([x,y])
print('union', np.union1d(x,y))
print('intersect', np.intersect1d(xy,[1,2,10]))
print('sorted descending', np.sort(xy)[::-1])


In [4]:
# 🖊️ TODO: split `xy` back into two equal halves using `np.array_split`
import numpy as np

x = np.array([1,3,5])
y = np.array([2,4,6])

xy = np.concatenate([x, y])

# Split into two equal halves
left, right = np.array_split(xy, 2)

print("left half:", left)    # [1 3 5]
print("right half:", right)  # [2 4 6]


left half: [1 3 5]
right half: [2 4 6]


## <a name='arithmetic'></a>7️⃣ Arithmetic Ops & Universal Functions

In [ ]:
v = np.arange(5)
print('exp', np.exp(v))
print('sin', np.sin(v))
print('vectorised addition', v + 10)


In [5]:
import numpy as np

# Given degrees
degrees = np.array([0, 30, 45, 60, 90])

# Convert degrees to radians (you can also use np.radians)
radians = np.deg2rad(degrees)

# Compute sine values (np.sin expects radians)
sines = np.sin(radians)

print("degrees:", degrees)
print("radians:", radians)
print("sin values:", sines)


degrees: [ 0 30 45 60 90]
radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
sin values: [0.         0.5        0.70710678 0.8660254  1.        ]


## <a name='broadcast'></a>8️⃣ Broadcasting Rules

Rules: compare dimensions from right → left; stretch size 1 dims; mismatch error.

In [ ]:
row = np.arange(5)
col = np.arange(3).reshape(3,1)
matrix = row + col  # broadcast to 3×5
print(matrix)


In [6]:
# 🖊️ TODO: use broadcasting to create a 10×10 multiplication table.
import numpy as np

# Create a row vector [1..10] and a column vector [1..10]
row = np.arange(1, 11).reshape(1, 10)   # shape (1,10)
col = np.arange(1, 11).reshape(10, 1)   # shape (10,1)

# Broadcasting multiplies each row element by each column element → (10,10)
mult_table = row * col

print(mult_table)



[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## <a name='stats'></a>9️⃣ Statistics & Aggregations

In [ ]:
data = np.random.default_rng(0).integers(1, 100, size=(5,4))
print('data\n', data)
print('row sums', data.sum(axis=1))
print('col means', data.mean(axis=0))


In [7]:
# 🖊️ TODO: compute `np.percentile` (25th, 50th, 75th) of flattened `data`.
import numpy as np

rng = np.random.default_rng(0)
data = rng.integers(1, 100, size=(5, 4))
print('data\n', data)
print('row sums', data.sum(axis=1))
print('col means', data.mean(axis=0))

# TODO: percentiles of flattened data
quartiles = np.percentile(data, [25, 50, 75])  # flattens by default (axis=None)
p25, p50, p75 = quartiles

print('25th percentile:', p25)
print('50th percentile (median):', p50)
print('75th percentile:', p75)


data
 [[85 64 51 27]
 [31  5  8  2]
 [18 81 65 91]
 [50 61 97 73]
 [63 54 56 93]]
row sums [227  46 255 281 266]
col means [49.4 53.  55.4 57.2]
25th percentile: 30.0
50th percentile (median): 58.5
75th percentile: 75.0


## <a name='random'></a>🔟 Random Numbers & Reproducibility

In [ ]:
rng = np.random.default_rng(42)
rand_floats = rng.random(5)
rand_ints = rng.integers(low=10, high=50, size=5)
print(rand_floats, rand_ints)
rng2 = np.random.default_rng(42)
assert np.allclose(rand_floats, rng2.random(5))


In [8]:
# 🖊️ TODO: simulate rolling a fair six‑sided die 100 times; estimate proportion of 6s.
import numpy as np

# Reuse a reproducible RNG
rng = np.random.default_rng(42)

# Simulate rolling a fair six-sided die 100 times (values 1..6)
rolls = rng.integers(low=1, high=7, size=100)

# Estimate the proportion of 6s
prop_sixes = np.mean(rolls == 6)

print("rolls:", rolls)
print("proportion of 6s:", prop_sixes)



rolls: [1 5 4 3 3 6 1 5 2 1 4 6 5 5 5 5 4 1 6 3 4 3 2 6 5 4 3 5 4 3 3 2 1 4 6 1 6
 5 2 4 1 5 5 3 1 6 3 6 5 5 5 2 3 3 3 1 4 1 5 5 6 5 3 6 3 2 6 3 1 3 5 2 3 1
 5 3 2 2 4 5 6 3 1 5 4 5 1 2 5 5 3 5 6 3 6 2 2 5 4 1]
proportion of 6s: 0.14


## <a name='structured'></a>1️⃣1️⃣ Structured / Record Arrays

In [ ]:
people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)],
                   dtype=[('name','U10'), ('age','i4'), ('weight','f4')])
print(people['name'], people['age'].mean())


In [9]:
# 🖊️ TODO: add a new field 'height' to the structured array using `np.lib.recfunctions.append_fields` (hint: pip install?).
import numpy as np

# Original structured array
people = np.array(
    [('Alice', 25, 55.0), ('Bob', 30, 85.5)],
    dtype=[('name','U10'), ('age','i4'), ('weight','f4')]
)

# If recfunctions import fails in your environment, ensure NumPy is installed/updated
# !pip install --upgrade numpy

from numpy.lib import recfunctions as rfn

# New height data (must match array length)
heights = np.array([165.0, 180.0], dtype='f4')  # centimeters, for example

# Append the new field 'height'
people_with_height = rfn.append_fields(
    people,
    names='height',
    data=heights,
    dtypes='f4',
    usemask=False
)

print(people_with_height)
print("fields:", people_with_height.dtype.names)
print("heights:", people_with_height['height'])


[('Alice', 25, 55. , 165.) ('Bob', 30, 85.5, 180.)]
fields: ('name', 'age', 'weight', 'height')
heights: [165. 180.]


## <a name='linalg'></a>1️⃣2️⃣ Linear Algebra Essentials

In [ ]:
A = np.random.random((3,3))
b = np.random.random(3)
x = np.linalg.solve(A, b)
print('A·x ≈ b?', np.allclose(A.dot(x), b))


In [ ]:
# 🖊️ TODO: compute eigenvalues of `A` using `np.linalg.eig`.


## <a name='io'></a>1️⃣3️⃣ File I/O (`npy`, `npz`, `txt`)

In [ ]:
np.save('array.npy', A)
loaded = np.load('array.npy')
print('loaded equals A?', np.allclose(loaded, A))
np.savez('multi_arrays.npz', A=A, b=b)


In [10]:
import numpy as np

# Recreate the same 'data' as in the stats section (or reuse your existing variable)
rng = np.random.default_rng(0)
data = rng.integers(1, 100, size=(5, 4))

# Save to CSV (comma-separated, with a header)
np.savetxt(
    'data.csv',
    data,
    delimiter=',',
    fmt='%d',                 # integers formatting; use '%.6f' for floats
    header='c1,c2,c3,c4',
    comments=''               # avoid the default '#' before header
)

# Load it back
loaded_data = np.loadtxt('data.csv', delimiter=',', skiprows=1)

print('Saved data:\n', data)
print('Reloaded data:\n', loaded_data)
print('Equal after round-trip?', np.array_equal(data, loaded_data.astype(int)))


Saved data:
 [[85 64 51 27]
 [31  5  8  2]
 [18 81 65 91]
 [50 61 97 73]
 [63 54 56 93]]
Reloaded data:
 [[85. 64. 51. 27.]
 [31.  5.  8.  2.]
 [18. 81. 65. 91.]
 [50. 61. 97. 73.]
 [63. 54. 56. 93.]]
Equal after round-trip? True


## <a name='datetime'></a>1️⃣4️⃣ Datetime64 & Timedelta64

In [ ]:
dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
delta = dates[1:] - dates[:-1]
print(dates[:5], delta[0])


In [11]:
import numpy as np

dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
delta = dates[1:] - dates[:-1]
print(dates[:5], delta[0])

# Monday=0, Tuesday=1, ..., Sunday=6
weekday_numbers = (dates - dates.astype('datetime64[W]')).astype(int)
num_mondays = np.count_nonzero(weekday_numbers == 0)

print("Number of Mondays:", num_mondays)


['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'] 1 days
Number of Mondays: 13


## <a name='mask'></a>1️⃣5️⃣ Masked Arrays & NaNs

In [ ]:
arr = np.array([1, 2, np.nan, 4, np.nan])
masked = np.ma.masked_invalid(arr)
print(masked.mean())


In [12]:
import numpy as np

# Example 2-D array with NaNs
A = np.array([
    [1.0,  2.0,  np.nan],
    [4.0,  np.nan, 6.0],
    [np.nan, 8.0,  9.0]
], dtype=float)

# Compute column means ignoring NaNs
col_means = np.nanmean(A, axis=0)

# Create a mask of NaN positions
mask = np.isnan(A)

# Replace NaNs with the corresponding column means
A[mask] = np.take(col_means, np.where(mask)[1])

print("Column means:", col_means)
print("Filled array:\n", A)


Column means: [2.5 5.  7.5]
Filled array:
 [[1.  2.  7.5]
 [4.  5.  6. ]
 [2.5 8.  9. ]]


## <a name='project'></a>1️⃣6️⃣ Mini‑Project: Fitness Data Analysis

Load `fitness.txt` (tab‑separated) then follow prompts.

In [18]:
import numpy as np

fitness = np.genfromtxt('fitness.txt', delimiter='\t', dtype=None, encoding=None, names=True)
print('columns:', fitness.dtype.names, 'rows:', len(fitness))


columns: ('date________step_count________mood________calories_burned________hours_of_sleep________bool_of_active________weight_kg',) rows: 96


In [19]:
import numpy as np
import pandas as pd

fitness = np.genfromtxt('fitness.txt', delimiter=None, dtype=None, encoding=None, names=True)

cols = [c.lstrip('#') for c in fitness.dtype.names]
fitness.dtype.names = tuple(cols)

df = pd.DataFrame(fitness)

df['date'] = pd.to_datetime(df['date'], format='%d-%m-%Y')
df['month'] = df['date'].dt.to_period('M')
df['week'] = df['date'].dt.isocalendar().week

monthly_steps = df.groupby('month')['step_count'].sum()
sleep_mood_corr = df['hours_of_sleep'].corr(df['mood'])
weekly_summary = df.groupby('week').agg({
    'step_count': 'sum',
    'hours_of_sleep': 'mean',
    'mood': 'mean',
    'calories_burned': 'sum'
})

print('Monthly Step Count:\n', monthly_steps)
print('\nSleep vs Mood Correlation:', sleep_mood_corr)
print('\nWeekly Summary:\n', weekly_summary)

Monthly Step Count:
 month
2017-10     79051
2017-11    103071
2017-12     89565
2018-01     10163
Freq: M, Name: step_count, dtype: int64

Sleep vs Mood Correlation: 0.2104166644730015

Weekly Summary:
       step_count  hours_of_sleep        mood  calories_burned
week                                                         
1           5833        3.714286  171.428571              168
2           4330        5.000000  250.000000                0
40         11530        6.000000  133.333333              378
41         23810        5.571429  114.285714              765
42         20669        6.428571  128.571429              657
43         16283        5.571429  214.285714              521
44         20598        5.142857  285.714286              665
45         31217        4.714286  285.714286             1012
46         17714        5.571429  285.714286              589
47         27859        5.714286  300.000000              917
48         18701        6.428571  257.142857        

## <a name='conclusion'></a>1️⃣7️⃣ Conclusion & Further Practice
Congrats on covering **all core NumPy topics** from your five lecture notebooks!

*Keep experimenting, read the official docs, and try converting your NumPy pipelines into Pandas or JAX for more fun.*